# Generated by Django 5.2 on 2025-04-20 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora_de_cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artefato',
            name='dano_critico',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artefato',
            name='taxa_critica',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artefato',
            name='valor_critico',
            field=models.FloatField(null=True),
        ),
    ]
